---
# Do not run this role every time
- name: Find recent run marker
  find:
    paths: /tmp
    pattern: '{{ role_name }}.{{ docker.cache_key }}.run-marker'
    age: -1h
  register: run_marker

- become: yes
  when: run_marker.files | length == 0 or not docker.enable_cache
  block:

  - include_tasks: setup.yml

  - vars:
      package: "docker-{{ docker.edition }}{{ (docker.package_version == '') | ternary('', '=' + docker.package_version) }}"
    become: yes
    block:

    - name: Install Docker
      package:
        name: "{{ package }}"
        state: "{{ docker.package_state }}"
        use: "apt"
      notify: Restart docker
      ignore_errors: "{{ ansible_check_mode or docker.ignore_install_errors }}"
      when: not docker.skip_docker_install

    - name: Install Python docker SDK for all users
      pip:
        name: docker
        umask: "0022"
      ignore_errors: "{{ docker.ignore_install_errors }}"

    - name: Set daemon_options
      set_fact:
        daemon_options: "{{ docker.tmpfs_storage.enable 
          | ternary(
              docker.daemon_options | combine({ 'data-root': docker.tmpfs_storage.path }),
              docker.daemon_options
            ) 
          }}"

    - name: Ensure /etc/docker/ directory exists
      file:
        path: /etc/docker
        state: directory
        mode: 0755
      when: daemon_options.keys() | length > 0

    - name: Configure Docker daemon options
      copy:
        content: "{{ daemon_options | to_nice_json }}"
        dest: /etc/docker/daemon.json
        mode: 0644
      when: daemon_options.keys() | length > 0
      notify: Restart docker

    - name: Create tmpfs for docker
      ansible.posix.mount:
        path: "{{ docker.tmpfs_storage.path }}"
        src: tmpfs
        fstype: tmpfs
        opts: nodev,nosuid,noexec,nodiratime,size={{ docker.tmpfs_storage.storage_size_gb }}
        state: mounted
      notify: Restart docker
      when: docker.tmpfs_storage.enable

    - name: Ensure Docker is started and enabled at boot
      service:
        name: docker
        state: "{{ docker.service_state }}"
        enabled: "{{ docker.service_enabled }}"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Ensure handlers are notified now to avoid firewall conflicts
      meta: flush_handlers

    - name: Create run marker
      file:
        path: /tmp/{{ role_name }}.{{ docker.cache_key }}.run-marker
        state: touch            