---
- vars:
    apt_repository: "deb [arch={{ docker.apt_arch }}] {{ docker.repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker.apt_release_channel }}"
    apt_gpg_key: "{{ docker.repo_url }}/{{ ansible_distribution | lower }}/gpg"
  when: not docker.skip_install
  become: yes
  block:

  - name: Ensure old versions of Docker are not installed
    package:
      name:
      - docker
      - docker-engine
      state: absent

  - name: Ensure dependencies are installed
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      state: present

  - name: Ensure additional dependencies are installed (on Ubuntu < 20.04 and any other systems)
    apt:
      name: gnupg2
      state: present
    when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is version('20.04', '<')

  - name: Ensure additional dependencies are installed (on Ubuntu >= 20.04)
    apt:
      name: gnupg
      state: present
    when: ansible_distribution == 'Ubuntu' or ansible_distribution_version is version('20.04', '>=')

  - name: Add Docker apt key
    apt_key:
      url: "{{ apt_gpg_key }}"
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    register: add_repository_key
    ignore_errors: "{{ docker.apt_ignore_key_error }}"

  - name: Ensure curl is present (on older systems without SNI)
    package: 
      name: curl 
      state: present
    when: add_repository_key is failed

  - name: Add Docker apt key (alternative for older systems without SNI)
    shell: >
      curl -sSL {{ apt_gpg_key }} | apt-key add -
    args:
      warn: false
    when: add_repository_key is failed

  - name: Add Docker repository
    apt_repository:
      repo: "{{ apt_repository }}"
      state: present
      update_cache: no
  
  - name: Apt update
    apt:
      update_cache: yes
      # Commented, otherwise it conflicts with common role
      # cache_valid_time: 36000
    # For Russia
    retries: 3
    delay: 10  

  # - name: Install postgres
  #   include_role:
  #     name: apt-install-by-regex
  #   vars: 
  #     apt_install_by_regex: 
  #       package_name: python3-docker
  #       package_version_regex: "{{ postgres.package_version_regex }}"
  #   failed_when: docker_ignore_failed_when  

  # Lessen version requirements so that ot would work on ubuntu 22.04 and 20.04
  - name: Install docker py library
    apt:
      name: python3-docker
    vars:
      docker_ignore_failed_when: "{{ docker.ignore_install_errors }}"
    failed_when: docker_ignore_failed_when      
