---
- name: Restart docker
  become: yes
  systemd:
    name: docker
    state: "{{ docker.restart_handler_state | default('restarted') }}"
    daemon_reload: yes
  failed_when: false # Предполагаем, что ошибок нет, но может потребоваться логика для конкретных ситуаций
